# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"run_process_in_foreground": "00_core.ipynb",
         "run_process_in_background": "00_core.ipynb",
         "jupyter_lab": "00_core.ipynb",
         "vscode": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://fastdaima.github.io/gpu_tpu_lab_server/"

git_url = "https://github.com/fastdaima/gpu_tpu_lab_server/tree/main/"

def custom_doc_links(name): return None
