# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://fastdaima.github.io/gpu_tpu_lab_server/"

git_url = "https://github.com/fastdaima/gpu_tpu_lab_server/tree/main/"

def custom_doc_links(name): return None
