# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['jupyter_lab', 'vscode']

# Cell
def jupyter_lab(lab: bool = True, dir_name: str = 'None') -> None:
    "starts jupyter lab server using localtunnel"
    from google.colab import drive
    drive.mount('/content/drive')
    if dir_name != 'None':
        path = '/content/drive/MyDrive/'+dir_name+'/'
    else:
        os.chdir('/content/drive/MyDrive/colab/')
    command = 'nohup jupyter lab --notebook-dir="/content/drive/MyDrive/colab" --no-browser --allow-root --ip="0.0.0.0" --port="6006" &'
    run_process_in_background(command)
    time.sleep(5)
    run_process_in_foreground('npx localtunnel --port 6006')


# Cell
def vscode(subdomain: str = 'fastdaima', port: int = 9000, config_save_path: str = '/content/drive/MyDrive/colab/.vscode') -> None:
    drive = import_module('google.colab.drive')
    drive.mount('/content/drive')
    run(['curl', '-fsSL', 'https://code-server.dev/install.sh', '-O'])
    run(['bash', 'install.sh', '--version', '3.10.2'])
    run(['pip3', 'install', 'flake8', '--user'])
    run(['pip3', 'install', 'black', '--user'])
    print(f'https://{subdomain}.loca.lt/?folder=/content/drive/MyDrive/colab')
    run_process_in_foreground(
        f'code-server --port {port} --auth none --disable-telemetry --force --user-data-dir {config_save_path} & npx localtunnel -p {port} -s {subdomain} --allow-invalid-cert')
